apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventureland-worker
  labels:
    app: adventureland-worker
spec:
  selector:
    matchLabels:
      app: adventureland-worker
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adventureland-worker
    spec:
      containers:
        - name: adventureland-bot
          image: 'ghcr.io/benhall-1/albotworker:main'
          imagePullPolicy: Always
          ports:
            - name: metrics-port
              containerPort: 3000
              protocol: TCP
          env:
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: adventureland-worker-cm
                  key: PASSWORD
            - name: EMAIL
              valueFrom:
                configMapKeyRef:
                  name: adventureland-worker-cm
                  key: EMAIL
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: adventureland-worker-cm
                  key: DATABASE_URL
          livenessProbe:
            httpGet:
              path: /kubernetes/liveliness
              port: 3000
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /kubernetes/health
              port: 3000
              scheme: HTTP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: adventureland-worker
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: metrics-port
  selector:
    app: adventureland-worker
  sessionAffinity: None
  type: LoadBalancer